extends Node

## Builds the global pixel-art UI theme at runtime.
##
## Autoload registration:
## Project > Project Settings > Globals > Autoload
## Select res://core/ui_theme.gd, set the name to UiTheme, and enable it.
##
## The font is generated by tools/build_pixel_font.py into art/fonts/, which
## sits outside the Godot project root for the same reason every other art file
## does. No ext_resource can cross that boundary, so the theme cannot be a
## static .tres and project.godot cannot point gui/theme/custom at one. It is
## assembled here instead and assigned to the scene tree root, from where Godot
## propagates it to every Control that does not override it.
##
## The trade-off is that the editor previews Controls with the default engine
## font; the pixel font only appears once the project is running.

const LOG_PREFIX := "[UI THEME]"
const FONT_DESCRIPTOR := "res://../art/fonts/metabolis_pixel_font.fnt"

## Matches NATIVE_SIZE in tools/build_pixel_font.py. Every font size used in
## the project MUST be a whole multiple of this, otherwise Godot samples the
## glyph atlas at a fractional scale and the pixel grid breaks up.
const NATIVE_FONT_SIZE := 10
const DEFAULT_FONT_SIZE := NATIVE_FONT_SIZE * 2

## Control types that get the font by name as well as through default_font.
## Godot looks up "font" per type first, so a type left out here would keep
## whatever the built-in default theme supplies.
const THEMED_CONTROL_TYPES := [
	"Label",
	"Button",
	"CheckBox",
	"CheckButton",
	"OptionButton",
	"LineEdit",
	"RichTextLabel",
	"TextEdit",
	"TooltipLabel",
	"PopupMenu",
	"ItemList",
	"Tree",
	"TabBar",
]

var pixel_font: FontFile
var pixel_theme: Theme


func _ready() -> void:
	pixel_font = _load_pixel_font()
	if pixel_font == null:
		# Every Control keeps the engine default font, so the game stays
		# playable and only looks wrong.
		push_warning(
			"%s Could not load '%s'; falling back to the engine font."
			% [LOG_PREFIX, FONT_DESCRIPTOR]
		)
		return

	# Godot resolves a Control's theme by walking up Control and Window parents
	# only. main.tscn's root is a Node2D, which severs that chain, so a Theme
	# assigned to the scene tree root never reaches the UI, and ThemeDB's
	# fallback font is already baked into the default theme before an autoload
	# runs. The project theme is the one lookup that is consulted from anywhere,
	# so the font is injected into it here.
	pixel_theme = ThemeDB.get_project_theme()
	if pixel_theme == null:
		push_warning(
			"%s No project theme; set gui/theme/custom in project.godot."
			% LOG_PREFIX
		)
		return

	_apply_font(pixel_theme, pixel_font)
	print("%s pixel theme applied at native size %d" % [LOG_PREFIX, NATIVE_FONT_SIZE])


## Rounds a requested size down to the nearest whole multiple of the font's
## native size, so callers can ask for a rough size and still land on the grid.
static func snap_font_size(requested: int) -> int:
	return maxi(NATIVE_FONT_SIZE, (requested / NATIVE_FONT_SIZE) * NATIVE_FONT_SIZE)


func _load_pixel_font() -> FontFile:
	var absolute_path := ProjectSettings.globalize_path(FONT_DESCRIPTOR)
	if not FileAccess.file_exists(absolute_path):
		return null
	var font := FontFile.new()
	if font.load_bitmap_font(absolute_path) != OK:
		return null

	# A BMFont arrives with fixed_size = NATIVE_FONT_SIZE and no scaling, so any
	# Control asking for a larger size gets nothing back and silently falls back
	# to the engine font. INTEGER_ONLY lets Godot scale the glyph atlas, but only
	# by whole factors, which is exactly the constraint pixel art needs anyway.
	font.fixed_size_scale_mode = TextServer.FIXED_SIZE_SCALE_INTEGER_ONLY
	return font


## Colors live in the .tres; only the font has to be injected at runtime.
func _apply_font(theme: Theme, font: FontFile) -> void:
	theme.default_font = font
	theme.default_font_size = DEFAULT_FONT_SIZE
	for control_type in THEMED_CONTROL_TYPES:
		theme.set_font("font", control_type, font)
		theme.set_font_size("font_size", control_type, DEFAULT_FONT_SIZE)
